/*
 * Waltz - Enterprise Architecture
 * Copyright (C) 2016, 2017, 2018, 2019 Waltz open source project
 * See README.md for more information
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific
 *
 */

package org.finos.waltz.model.survey;


import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.finos.waltz.model.DescriptionProvider;
import org.finos.waltz.model.IdProvider;
import org.finos.waltz.model.IdSelectionOptions;
import org.finos.waltz.model.NameProvider;
import org.immutables.value.Value;

import java.time.LocalDate;
import java.util.Optional;
import java.util.Set;

@Value.Immutable
@JsonSerialize(as = ImmutableSurveyRun.class)
@JsonDeserialize(as = ImmutableSurveyRun.class)
public abstract class SurveyRun implements IdProvider, NameProvider, DescriptionProvider {

    public abstract Long surveyTemplateId();
    public abstract IdSelectionOptions selectionOptions();
    public abstract Set<Long> involvementKindIds();
    public abstract Optional<LocalDate> issuedOn();
    public abstract LocalDate dueDate();
    public abstract LocalDate approvalDueDate();
    public abstract SurveyIssuanceKind issuanceKind();
    public abstract Long ownerId();
    public abstract String contactEmail();
    public abstract SurveyRunStatus status();
    public abstract Set<Long> ownerInvKindIds();

    @Value.Default
    public boolean isDefault() {
        return false;
    }

    @Value.Default
    public SurveyInvolvementResolutionKind involvementResolutionKind() {
        return SurveyInvolvementResolutionKind.TARGET_ENTITY;
    }

    /**
     * When true, an instance generated by this run - if it has no saved responses yet at the point it is
     * first opened - is prefilled from the latest APPROVED instance of the same template sharing the same
     * target entity (and qualifier entity, where applicable), for whichever questions are still compatible
     * with the current template.
     */
    @Value.Default
    public boolean prefillFromLastApprovedInstance() {
        return false;
    }
}
